// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrBiTUwujGxQtB1YVZD-Y57X-duPy1Chc',
    appId: '1:823946262338:web:6ef7a57b089e538b0f3adb',
    messagingSenderId: '823946262338',
    projectId: 'boumed-store-7ff42',
    authDomain: 'boumed-store-7ff42.firebaseapp.com',
    storageBucket: 'boumed-store-7ff42.appspot.com',
    measurementId: 'G-ETRDBCWHJQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_LznvWS7zff7pKIwK0NBmnKkd99kgvF4',
    appId: '1:823946262338:android:bf0a5d4e2b839ece0f3adb',
    messagingSenderId: '823946262338',
    projectId: 'boumed-store-7ff42',
    storageBucket: 'boumed-store-7ff42.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCuMEM9uP22yBppMe7bYwNaNLkuHVv6kw',
    appId: '1:823946262338:ios:bac1022d2b82b0fe0f3adb',
    messagingSenderId: '823946262338',
    projectId: 'boumed-store-7ff42',
    storageBucket: 'boumed-store-7ff42.appspot.com',
    iosBundleId: 'com.example.boumedstore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCuMEM9uP22yBppMe7bYwNaNLkuHVv6kw',
    appId: '1:823946262338:ios:bac1022d2b82b0fe0f3adb',
    messagingSenderId: '823946262338',
    projectId: 'boumed-store-7ff42',
    storageBucket: 'boumed-store-7ff42.appspot.com',
    iosBundleId: 'com.example.boumedstore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrBiTUwujGxQtB1YVZD-Y57X-duPy1Chc',
    appId: '1:823946262338:web:f975b93e08e962170f3adb',
    messagingSenderId: '823946262338',
    projectId: 'boumed-store-7ff42',
    authDomain: 'boumed-store-7ff42.firebaseapp.com',
    storageBucket: 'boumed-store-7ff42.appspot.com',
    measurementId: 'G-911T9C4T44',
  );
}
